#!/bin/bash

USAGE="slides-courses filename.xml"

SLIDE_PATH=/Library/Server/Web/Data/Sites/Default/courses-presentations/common/xslt/

CLASS_PATH=$SLIDE_PATH/xalan/serializer.jar
CLASS_PATH=$CLASS_PATH:$SLIDE_PATH/xalan/serializer.jar
CLASS_PATH=$CLASS_PATH:$SLIDE_PATH/xalan/xercesImpl.jar
CLASS_PATH=$CLASS_PATH:$SLIDE_PATH/xalan/xml-apis.jar
CLASS_PATH=$CLASS_PATH:$SLIDE_PATH/xalan/xalan.jar
CLASS_PATH=$CLASS_PATH:$SLIDE_PATH/xalan/xsltc.jar
CLASS_PATH=$CLASS_PATH:$SLIDE_PATH/

# Check if arg is null
if [ -n "$1" ]; then

    java -classpath $CLASS_PATH  xslt $1 $SLIDE_PATH/slides-courses.xsl index.html

else
  echo Usage: "$USAGE"
fi


